name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to external Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image to registry
        run: |
          cd swagger
          docker build ./ -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_REGISTRY }}/regolo/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_REGISTRY }}/regolo/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/regolo/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/regolo/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Log out from external Docker registry
        run: docker logout ${{ secrets.DOCKER_REGISTRY }}
